sonar.projectKey=bckirkup_Garlic-Routed-Local-Area-Network-Domain
sonar.organization=bckirkup
sonar.sources=src,scripts
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
